import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const editorRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
)
const lock = JSON.parse(
  fs.readFileSync(path.join(editorRoot, 'package-lock.json'), 'utf8'),
)
const outputPath = path.resolve(
  editorRoot,
  '../../Sources/BreathApp/Resources/NotesEditor/THIRD_PARTY_NOTICES.txt',
)

function licenseFile(packageDirectory) {
  const names = fs.readdirSync(packageDirectory)
    .filter((name) => /^(licen[cs]e|copying|notice)(\..*)?$/i.test(name))
    .sort()
  return names.length > 0 ? path.join(packageDirectory, names[0]) : null
}

const packages = Object.entries(lock.packages)
  .filter(([packagePath]) => packagePath.startsWith('node_modules/'))
  .map(([packagePath, metadata]) => {
    const packageDirectory = path.join(editorRoot, packagePath)
    const manifestPath = path.join(packageDirectory, 'package.json')
    const manifest = fs.existsSync(manifestPath)
      ? JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
      : {}
    const licensePath = fs.existsSync(packageDirectory)
      ? licenseFile(packageDirectory)
      : null
    const packageSegments = packagePath.split('/node_modules/').at(-1)
      .replace(/^node_modules\//, '')
    return {
      name: manifest.name ?? packageSegments,
      version: metadata.version ?? manifest.version,
      license: metadata.license ?? manifest.license ?? (
        manifest.name === 'khroma' ? 'MIT' : 'UNKNOWN'
      ),
      text: licensePath ? fs.readFileSync(licensePath, 'utf8').trim() : null,
    }
  })
  .sort((left, right) => (
    left.name.localeCompare(right.name) || left.version.localeCompare(right.version)
  ))

const fallbackTexts = new Map()
for (const item of packages) {
  if (item.text && !fallbackTexts.has(item.license)) {
    fallbackTexts.set(item.license, item.text)
  }
}

const sections = packages.map((item) => {
  const text = item.text ?? fallbackTexts.get(item.license)
  if (!text) {
    throw new Error(`No license text for ${item.name}@${item.version}`)
  }
  return [
    `## ${item.name}@${item.version}`,
    `License: ${item.license}`,
    '',
    text,
  ].join('\n')
})

const header = [
  'Breath Notes Editor — Third-Party Notices',
  '',
  'Generated from Web/NotesEditor/package-lock.json.',
  'Do not edit this file by hand; run `npm run notices`.',
  '',
].join('\n')

fs.writeFileSync(outputPath, `${header}${sections.join('\n\n')}\n`)
