#!/usr/bin/env swift

import Foundation

struct Theme {
    let name: String
    let background: UInt32
    let foreground: UInt32
    let cursor: UInt32
    let cursorText: UInt32
    let selectionBackground: UInt32
    let selectionForeground: UInt32
    let ansi: [UInt32]
}

enum GenerationError: Error, CustomStringConvertible {
    case usage
    case invalidTheme(String)

    var description: String {
        switch self {
        case .usage:
            "usage: generate-ghostty-theme-catalog.swift <themes-directory> <output-file>"
        case let .invalidTheme(message):
            message
        }
    }
}

func parseColor(_ value: String, theme: String, key: String) throws -> UInt32 {
    let hex = value.trimmingCharacters(in: .whitespacesAndNewlines)
    guard hex.hasPrefix("#"),
          hex.count == 7,
          let color = UInt32(hex.dropFirst(), radix: 16)
    else {
        throw GenerationError.invalidTheme(
            "\(theme): invalid \(key) color \(value)"
        )
    }
    return color
}

func parseTheme(at url: URL) throws -> Theme {
    let name = url.lastPathComponent
    let contents = try String(contentsOf: url, encoding: .utf8)
    var values: [String: UInt32] = [:]
    var ansi: [UInt32?] = Array(repeating: nil, count: 16)

    for rawLine in contents.split(whereSeparator: \.isNewline) {
        let parts = rawLine.split(separator: "=", maxSplits: 1)
        guard parts.count == 2 else { continue }
        let key = parts[0].trimmingCharacters(in: .whitespaces)
        let value = parts[1].trimmingCharacters(in: .whitespaces)
        if key == "palette" {
            let paletteParts = value.split(separator: "=", maxSplits: 1)
            guard paletteParts.count == 2,
                  let index = Int(paletteParts[0].trimmingCharacters(in: .whitespaces)),
                  ansi.indices.contains(index)
            else {
                throw GenerationError.invalidTheme(
                    "\(name): invalid palette entry \(value)"
                )
            }
            ansi[index] = try parseColor(
                String(paletteParts[1]),
                theme: name,
                key: "palette \(index)"
            )
        } else {
            values[key] = try parseColor(value, theme: name, key: key)
        }
    }

    func required(_ key: String) throws -> UInt32 {
        guard let value = values[key] else {
            throw GenerationError.invalidTheme("\(name): missing \(key)")
        }
        return value
    }

    guard ansi.allSatisfy({ $0 != nil }) else {
        throw GenerationError.invalidTheme("\(name): incomplete 16-color palette")
    }

    return try Theme(
        name: name,
        background: required("background"),
        foreground: required("foreground"),
        cursor: required("cursor-color"),
        cursorText: required("cursor-text"),
        selectionBackground: required("selection-background"),
        selectionForeground: required("selection-foreground"),
        ansi: ansi.map { $0! }
    )
}

func swiftString(_ value: String) throws -> String {
    let data = try JSONEncoder().encode(value)
    return String(decoding: data, as: UTF8.self)
}

func hex(_ value: UInt32) -> String {
    String(format: "0x%06X", value)
}

do {
    guard CommandLine.arguments.count == 3 else {
        throw GenerationError.usage
    }
    let themesURL = URL(fileURLWithPath: CommandLine.arguments[1], isDirectory: true)
    let outputURL = URL(fileURLWithPath: CommandLine.arguments[2])
    let urls = try FileManager.default.contentsOfDirectory(
        at: themesURL,
        includingPropertiesForKeys: [.isRegularFileKey],
        options: [.skipsHiddenFiles]
    )
    let themes = try urls
        .filter { try $0.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile == true }
        .map(parseTheme)
        .sorted {
            $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending
        }

    var output = """
    // Generated by scripts/generate-ghostty-theme-catalog.swift.
    // Source: Ghostty's pinned iterm2_themes dependency. Do not edit by hand.

    struct GhosttyThemeDefinition: Sendable {
        let name: String
        let palette: TerminalColorPalette

        init(
            _ name: String,
            _ background: UInt32,
            _ foreground: UInt32,
            _ cursor: UInt32,
            _ cursorText: UInt32,
            _ selectionBackground: UInt32,
            _ selectionForeground: UInt32,
            _ ansi: [UInt32]
        ) {
            self.name = name
            palette = TerminalColorPalette(
                background: TerminalRGBColor(hex: background),
                foreground: TerminalRGBColor(hex: foreground),
                cursor: TerminalRGBColor(hex: cursor),
                cursorText: TerminalRGBColor(hex: cursorText),
                selectionBackground: TerminalRGBColor(hex: selectionBackground),
                selectionForeground: TerminalRGBColor(hex: selectionForeground),
                ansiColors: ansi.map(TerminalRGBColor.init(hex:))
            )
        }
    }

    enum GhosttyThemeCatalog {
        static let definitions: [GhosttyThemeDefinition] = [

    """

    for theme in themes {
        let name = try swiftString(theme.name)
        let colors = [
            theme.background,
            theme.foreground,
            theme.cursor,
            theme.cursorText,
            theme.selectionBackground,
            theme.selectionForeground,
        ].map(hex).joined(separator: ", ")
        let ansi = theme.ansi.map(hex).joined(separator: ", ")
        output += "        .init(\(name), \(colors), [\(ansi)]),\n"
    }

    output += """
        ]

        private static let definitionsByName = Dictionary(
            uniqueKeysWithValues: definitions.map { ($0.name, $0) }
        )

        static func definition(named name: String) -> GhosttyThemeDefinition? {
            definitionsByName[name]
        }
    }

    """

    try output.write(to: outputURL, atomically: true, encoding: .utf8)
    print("Generated \(themes.count) Ghostty themes at \(outputURL.path)")
} catch {
    FileHandle.standardError.write(Data("\(error)\n".utf8))
    exit(1)
}
